# Machine Learning for Pneumonia Detection: Convolutional Neural Networks In Image Recognition

title: "Machine Learning for Pneumonia Detection: Convolutional Neural Networks In Image Recognition"
description: "This project uses VGG16 model with fine-tuning, data augmentation, learning rate adjustments, and epoch changes to detect pneumonia in chest X-rays."

# Table of Contents
table_of_contents:
  - name: "What Have I Learned"
    link: "#0-what-have-i-learned"
  - name: "Introduction"
    link: "#1-introduction"
  - name: "Initial Version (Pre-Improvements)"
    link: "#2-initial-version-pre-improvements"
  - name: "Improved Version (Post-Improvements)"
    link: "#3-improved-version-post-improvements"
  - name: "Analysis of Changes"
    link: "#4-analysis-of-changes"
  - name: "Conclusion"
    link: "#5-conclusion"
  - name: "Code"
    link: "#code"

# What Have I Learned
what_have_i_learned:
  - "Deep Learning Frameworks & Model Architecture - Convolutional Neural Networks, TensorFlow/Keras"
  - "Model Optimization - Fine-tuning, Data Augmentation, Hyperparameter Tuning"
  - "Performance Metrics & Model Evaluation - Accuracy and Loss Analysis"
  - "Training Process Management & Evaluation - Early Stopping, Performance Metrics Analysis"
  - "Validation Techniques - Cross-Validation"

# Initial Version (Pre-Improvements)
initial_version:
  model: "VGG16"
  data_augmentation:
    rotation_range: "20 degrees"
    width_shift: "0.2"
    height_shift: "0.2"
    shear_zoom_range: "0.2"
    brightness_adjustment: "[0.8, 1.2]"
    channel_shift: "20.0"
    vertical_flip: "Enabled"
  learning_rate: 0.001
  epochs: 3
  callbacks: 
    - "Early stopping with patience = 2"
    - "Restoring the best model weights"
  results:
    accuracy: "~80.6%"
    loss: "~0.4658"

# Improved Version (Post-Improvements)
improved_version:
  model: "VGG16"
  data_augmentation:
    rotation_range: "25 degrees"
    width_shift: "0.3"
    height_shift: "0.3"
    shear_zoom_range: "0.3"
    brightness_adjustment: "[0.7, 1.3]"
    channel_shift: "30.0"
    vertical_flip: "Enabled"
  learning_rate: 0.0001
  epochs: 10
  callbacks: 
    - "Early stopping with patience = 3"
    - "Restoring the best model weights"
  results:
    accuracy: "~80.6%"
    loss: "~0.4658"

# Analysis of Changes
analysis_of_changes:
  - name: "Data Augmentation"
    description: "Increased data augmentation to prevent overfitting, but it did not significantly affect test accuracy."
  - name: "Fine-tuning"
    description: "Fine-tuning the last four layers allowed for more dataset-specific learning. Despite this, accuracy remained unchanged."
  - name: "Learning Rate"
    description: "Reducing the learning rate allowed for finer weight updates, but test accuracy remained the same."
  - name: "Epochs"
    description: "Increasing epochs provided more learning time, but early stopping prevented overfitting. No significant performance changes."

# Conclusion
conclusion:
  - "Changes made in the model, including data augmentation, fine-tuning, and learning rate adjustments, resulted in negligible improvements."
  - "Test accuracy remained at ~80.6% before and after improvements."
  - "Experimenting with other models like ResNet50 or InceptionV3 could yield better results."
  - "Further hyperparameter tuning and ensemble models may improve performance."

# Code
code_location: "https://github.com/Xenizal/Python_Project"
dataset: "https://www.kaggle.com/datasets/paultimothymooney/chest-xray-pneumonia/data"
